with-expecter: true
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
filename: "mock_{{.InterfaceName | snakecase}}.go"
packages:
  github.com/SturlaSolheim/mediaCircleBackend/repository:
    interfaces:
      AlbumRepositoryInterface:
        config:
          dir: "mocks"