generate:
  models: true
  client: false
  server: true
  spec: false
  embedded-spec: false
output-options:
  skip-prune: true
  include-tags:
    - albums
  exclude-tags: []
package: generated
output: ./generated/albums_handler.go