// Code generated by mockery v2.53.5. DO NOT EDIT.

package repository

import (
	models "github.com/SturlaSolheim/mediaCircleBackend/models"
	mock "github.com/stretchr/testify/mock"
)

// MockAlbumRepositoryInterface is an autogenerated mock type for the AlbumRepositoryInterface type
type MockAlbumRepositoryInterface struct {
	mock.Mock
}

type MockAlbumRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAlbumRepositoryInterface) EXPECT() *MockAlbumRepositoryInterface_Expecter {
	return &MockAlbumRepositoryInterface_Expecter{mock: &_m.Mock}
}

// FindAll provides a mock function with no fields
func (_m *MockAlbumRepositoryInterface) FindAll() ([]models.Album, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []models.Album
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Album, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Album); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Album)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlbumRepositoryInterface_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockAlbumRepositoryInterface_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *MockAlbumRepositoryInterface_Expecter) FindAll() *MockAlbumRepositoryInterface_FindAll_Call {
	return &MockAlbumRepositoryInterface_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *MockAlbumRepositoryInterface_FindAll_Call) Run(run func()) *MockAlbumRepositoryInterface_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAlbumRepositoryInterface_FindAll_Call) Return(_a0 []models.Album, _a1 error) *MockAlbumRepositoryInterface_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlbumRepositoryInterface_FindAll_Call) RunAndReturn(run func() ([]models.Album, error)) *MockAlbumRepositoryInterface_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: album
func (_m *MockAlbumRepositoryInterface) Save(album *models.Album) error {
	ret := _m.Called(album)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Album) error); ok {
		r0 = rf(album)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAlbumRepositoryInterface_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockAlbumRepositoryInterface_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - album *models.Album
func (_e *MockAlbumRepositoryInterface_Expecter) Save(album interface{}) *MockAlbumRepositoryInterface_Save_Call {
	return &MockAlbumRepositoryInterface_Save_Call{Call: _e.mock.On("Save", album)}
}

func (_c *MockAlbumRepositoryInterface_Save_Call) Run(run func(album *models.Album)) *MockAlbumRepositoryInterface_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Album))
	})
	return _c
}

func (_c *MockAlbumRepositoryInterface_Save_Call) Return(_a0 error) *MockAlbumRepositoryInterface_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAlbumRepositoryInterface_Save_Call) RunAndReturn(run func(*models.Album) error) *MockAlbumRepositoryInterface_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAlbumRepositoryInterface creates a new instance of MockAlbumRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAlbumRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAlbumRepositoryInterface {
	mock := &MockAlbumRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
